apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- expensetrack-ingress.yaml

namespace: expensetrack

images:
- name: expensetrackapi
  newName: raphacbs/api-expense-track
  newTag: fa928f3796aa302531ff1bf13a6cf19618db8c94
