apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- expensetrack-ingress.yaml
- certificate.yaml
- clusterissuer.yaml
- pvc.yaml
- storegeclass.yaml

namespace: expensetrack

images:
- name: expensetrackapi
  newName: raphacbs/api-expense-track
  newTag: b79a31efd5c993d7c9383b6488081d243c527d73
