apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: expensetrack

images:
- name: expensetrackapi
  newName: raphacbs/api-expense-track
  newTag: 0b316829b7a618cd1b1e9766bfd44b32e7bfd2be
